/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "exti_driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_Init();
	GPIOC->GPIO_BSRR = (1<<(13+16));
	EXTI_Init(EXTI_MODE_INTERRUPT,EXTI_LINE_1,EXTI_TRIGGER_FALLING,EXTI_GPIOA);
    /* Loop forever */
	while(1)
	{

	}
}

void EXTI1_IRQHandler(void)
{
	if (EXTI->EXTI_PR & (1<<1)) { // Kiểm tra cờ ngắt Line 1
		EXTI->EXTI_PR |= (1<<1);  // Hạ cờ ngắt (Ghi 1 để xóa)
		GPIOC->GPIO_BSRR = (1<<13);
	}
}
